name: build
channels:
  - conda-forge
  - mdtools
dependencies:
  # Base dependencies
  - python
  - pip
  - chemprop

  # Conda build
  - anaconda-client
  - conda-build
  - boa

  # PyPI build
  - pip:
    - build
    - twine
